import pandas as pd

# create a dataframe to hold products and attributes
attr = ['Name', 'Price', 'Description', 'Tag', 'Subtag', 'Image Link']
df = pd.DataFrame(columns=attr)
df = df.fillna(0)

# omitted museums with free admission to all, hence no ticketing needed
# standard adult price for tourists (most of these are free admission for Sporeans)
df.loc[len(df)] = ['National Museum of Singapore', '$15', 'Oldest museum in Singapore, with history dating back to 1887.', 'Museums', 'History', 'https://upload.wikimedia.org/wikipedia/commons/6/6f/2016_Singapur%2C_Museum_Planning_Area%2C_Narodowe_Muzeum_Singapuru_%2802%29.jpg']
df.loc[len(df)] = ['Asian Civilisations Museum', '$8', 'Opened in 1997, the museum is devoted to exploring the rich artistic heritage of Asia, especially the ancestral cultures of Singaporeans', 'Museums', 'History', 'https://upload.wikimedia.org/wikipedia/commons/9/9e/Asian_civilisations_museums_singapore.jpg']
df.loc[len(df)] = ['ArtScience Museum', '$19', 'ArtScience Museum is an iconic cultural landmark in Singapore. Our mission is to explore where art, science, culture and technology come together.', 'Museums', 'Art/Design', 'https://upload.wikimedia.org/wikipedia/commons/f/f3/ArtScience_Museum%2C_Marina_Bay_Sands%2C_Singapore.jpg']
df.loc[len(df)] = ['Indian Heritage Center', '$8', 'The Indian Heritage Centre traces the history of the Indian and South Asian communities in the Southeast Asian region.', 'Museums', 'History', 'https://www.indianheritage.gov.sg/en/-/media/ihc2017/images/about-us/about.jpg?la=en']
df.loc[len(df)] = ['Lee Kong Chian Natural History Museum', '$20', 'The Lee Kong Chian Natural History Museum strives to be a leader in Southeast Asian biodiversity – in research, education and outreach.', 'Museums', 'History', 'https://uci.nus.edu.sg/oed/wp-content/uploads/sites/7/2018/07/LK02A-1.jpg']
df.loc[len(df)] = ['Fort Canning Battlebox', '$15', 'Embark on an unforgettable journey 9 metres underground into the Battlebox, an authentic World War II secret underground command centre built in the late 1930s.', 'Museums', 'History', 'https://www.battlebox.com.sg/uploads/1/2/0/1/120161686/editor/battlebox-visitor-centre_1.jpg']
df.loc[len(df)] = ['Red Dot Museum', '$6.40', 'Red Dot Design Museum is the physical embodiment of the international Red Dot Design Award — one of the largest design awards in the World.', 'Museums', 'Art/Design', 'https://www.visitsingapore.com/see-do-singapore/arts/museums-galleries/red-dot-design-museum/jcr:content/par/column_control/ccpar1/content_img_insta/content/item_1.thumbnail.image-path.700.394.jpg']
df.loc[len(df)] = ['Malay Heritage Centre', '$8', 'Officially opened by Prime Minister Lee Hsien Loong in June 2005, the Malay Heritage Centre (MHC) provides wonderful cultural exposure and learning opportunities for visitors of all ages and interests.', 'Museums', 'History', 'https://upload.wikimedia.org/wikipedia/commons/c/c8/Malay_Heritage_Centre%2C_2012.jpg']
df.loc[len(df)] = ['Former Ford Factory', '$3', 'The Ford Motor Company which was first established in Singapore at Anson Road in 1926, moved to its new state-of-the-art factory located at Upper Bukit Timah Road in October 1941.', 'Museums', 'History', 'https://upload.wikimedia.org/wikipedia/commons/2/22/Old_Ford_Motor_Factory_-_www.joyofmuseums.com_-_external.jpg']
df.loc[len(df)] = ['Singapore Musical Box Museum', '$12', "In this Singapore's first musical box museum, we aim to share the historical background from the rise to the fall of the musical boxes to how it made its way to Singapore in the 19th century to the public.", 'Museums', 'History', 'https://images.squarespace-cdn.com/content/v1/557e7f73e4b0ff7f4a6b68f1/1465535317496-GCMEBBZ843ZUONHYCAKZ/ke17ZwdGBToddI8pDm48kL4WrIntsHuCODFzGytxs8sUqsxRUqqbr1mOJYKfIPR7ghj6HvfcmhHlMvf2scXKbxT9cQy7WwNocDo6aSzGJ7rFhSPlVV71_Xhqg_adcQJMFKHYhK9lS0S7UT3enC3Ockx_RzqjhTytA60HOLZKeT5mprCx02GhU-2G4N-JnQGI/Front.JPG?format=1500w']
df.loc[len(df)] = ['Chinatown Heritage Centre', '$18', 'Restored shophouses displaying living spaces, furnishings & artifacts of early Chinatown settlers.', 'Museums', 'History', 'https://www.chinatownheritagecentre.com.sg/wp-content/uploads/2020/09/WhatsApp-Image-2020-09-11-at-4.59.13-PM.jpeg']
df.loc[len(df)] = ['Singapore Discovery Centre', '$10', 'Singapore Discovery Centre (SDC) is a non-profit organisation whose mission is to share the Singapore Story and inspire a desire to contribute to Singapore’s future.', 'Museums', 'History', 'https://upload.wikimedia.org/wikipedia/commons/d/d9/Singapore_Discovery_Centre_-_20080219-01.jpg']
df.loc[len(df)] = ['Trick Eye Museum', '$21.25', 'Trick Eye Museum brings you closer to art through the use of optical illusions. Immerse yourself in different settings at 6 themed zones and recreate into memorable photographs with your imagination.', 'Museums', 'Art/Design', 'https://www.rwsentosa.com/-/media/project/non-gaming/rwsentosa/attractions/trick-eye-museum/trick-eye-museum-overview-trick-1366x666.jpg?h=268&la=en&w=550&hash=47B3988EACC27FCC530D725763FD0DA7CB6E7D00']
df.loc[len(df)] = ['Vintage Cameras Museum', '$20', "The Vintage Camera's Museum, itself is set in the form of a camera, and the entry is shaped like a lens.", 'Museums', 'History', 'http://www.vintagecamerasmuseumsg.com/admin/views/pressrelease/211117094447.jpg']

print(df)
df.to_csv('museum_result.csv')
