"""CREATE DATABASE ticketDB;
CREATE TABLE IF NOT EXISTS ACCOUNT (USER_ID INT AUTO_INCREMENT PRIMARY KEY, EMAIL VARCHAR (255) NOT NULL, PASSWORD VARCHAR (512), UNIQUE (EMAIL));"""
"""INSERT INTO ACCOUNT (EMAIL, PASSWORD)
VALUES ('test@gmail.com','test1');"""
