"""CREATE DATABASE ticketDB;
CREATE TABLE account (id INT NOT NULL AUTO_INCREMENT, email VARCHAR(255) NOT NULL, password_salt VARCHAR(255) NOT NULL, password_hash VARCHAR(255) NOT NULL, PRIMARY KEY (id), UNIQUE (email));"""
"""INSERT INTO ACCOUNT (EMAIL, PASSWORD)
VALUES ('test@gmail.com','test1');"""
